import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarDesktop from "@/components/Navbar/navbarDesktop";
import FooterDesktop from "@/components/Footer/footerDesktop";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Appify",
    template: "%s | Appify ",
  },
  description:
    "Generated by next.js - Appify is a modern landing page focused on UX, validation, and modern architecture",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div className="pt-[3vh] md:pt-[6vh] ">
          <NavbarDesktop />
          {modal}
          {children}
          <FooterDesktop />
        </div>
      </body>
    </html>
  );
}
