import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarDesktop from "@/components/Navbar/navbarDesktop";
import FooterDesktop from "@/components/Footer/footerDesktop";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Appity",
    template: "%s | Appity ",
  },
  description: "Generated by next.js - Create App landing page example  ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <NavbarDesktop />
        {children}
        <FooterDesktop />
      </body>
    </html>
  );
}
